const InventoryActionTypes = {
  SET_CATEGORY_LIST: 'SET_CATEGORY_LIST',
  SET_BRAND_LIST: 'SET_BRAND_LIST',
  SET_PRODUCTS_LIST: 'SET_PRODUCTS_LIST',
  SET_SEARCH_LIST: 'SET_SEARCH_LIST',
  SET_SEARCH_CATEGORY_LIST: 'SET_SEARCH_CATEGORY_LIST',
  SET_SEARCH_BRAND_LIST: 'SET_SEARCH_BRAND_LIST',
};

export default InventoryActionTypes;
